module.exports = {
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_PLACE_API_KEY: process.env.GOOGLE_PLACE_API_KEY,
  JWT_SECRET: process.env.JWT_SECRET,
  MONGO_URI: String(process.env.MONGO_URI),
  SESSION_SECRET: process.env.SESSION_SECRET,
};
